### ISSUE TITLE
Improve Basis function

### ISSUE THREAD

**Issue by edgarcosta** [edgarcosta/hilbertmodularforms#11]
At the moment only works for level 1, as we have mostly ignored characters so far see #12.

**Comment by michaelmusty** [comment]
As @jvoight mentioned in the last meeting, at least for a basis of Eisenstein series we should be trying to generalize Theorems 4.5.2 and 4.6.2 in Diamond and Shurman.

With notation as in Dasgupta-Darmon-Pollack, it appears that
  E_k(eta,psi)
belongs to
  M_k(Gamma_0(NN), chi)
where
  chi = eta*psi
(not the inverse).

**Comment by edgarcosta** [comment]
`EisensteinBasis` now works for parallel weight and with character.

`Basis` works for parallel weight, trivial character (due to the building dependence), and any level
