### ISSUE TITLE
+:= and *:=

### ISSUE THREAD

**Issue by jvoight** [edgarcosta/hilbertmodularforms#122]
It would be useful to have versions of arithmetic operations which perform the operation on the existing object (overwriting it), to save space and time creating a new one.

**Comment by SamSchiavone** [comment]
I think this already works.

```
> f := E2;
> f +:= 4*E2;
> f eq 5*E2;
true
> f -:= 8*E2;
> f eq -3*E2;
true
> f := E2;
> f *:= E2;
> f eq E2^2;
true
```
