### ISSUE TITLE
Convert Hecke characters to Dirichlet characters

### ISSUE THREAD

**Issue by jvoight** [edgarcosta/hilbertmodularforms#126]

**Comment by edgarcosta** [comment]
I'm confused about this one, but I think we agreed that we should be using Hecke characters.

**Comment by BenKBreen** [comment]
We are working on write-up for this

**Comment by edgarcosta** [comment]
@BenKBreen, tks. Looking forward as I'm still mathematically confused, but have not invested much time in it.

Regardless, now I think this change makes sense, just from the practical perspective that Magma internally reduces almost everything to Dirichlet restriction, so there is not much point in working with `GrpHeckeElt` when Magma internally does all the work with `GrpDrchNFElt`.

**Comment by edgarcosta** [comment]
After talking with @assaferan I think we agreed to stick with Hecke

**Comment by jvoight** [comment]
Hecke yeah!  We need both, but (in Magma) a Hecke character knows its Dirichlet character.
