### ISSUE TITLE
Figure out formal sums

### ISSUE THREAD

**Issue by edgarcosta** [edgarcosta/hilbertmodularforms#134]
Here are some options:
1- Have an associative array indexed on `<bb, unitchar>`
2- Have a double associative array indexed `bb` and then `unitchar`

Should we make a new type for this? Don't we have enough already?

How are we going to use this?

**Comment by jvoight** [comment]
When we pull back Siegel Eisenstein series, we obtain a form f on SL(R + R^#) which we can decompose into its plus and minus forms f = fplus + fminus.  The form fplus is on GL^+(R + R^#) so we can recognize it in our graded ring.  We worked hard to implement a way to work with fminus, having nontrivial unit character (value -1 on a totally positive fundamental unit): in particular, we can compute fminus^2 (having trivial unit character) and recognize it.  

Still, we would like to add them back together to get a form f.  

We do have a lot of types already, and I can see some advantages and disadvantages of various proposals!  The simplest one is to just not allow this for now.

**Comment by edgarcosta** [comment]
See #135 and #136
