### ISSUE TITLE
Fix CanonicalRing

### ISSUE THREAD

**Issue by edgarcosta** [edgarcosta/hilbertmodularforms#137]
@ababei, can you give me some details?

**Comment by ababei** [comment]
I am running the following code, to compute the canonical ring on a component:


> prec := 10;
> D := 12;
> F:=QuadraticField(12);
> GrRing := GradedRingOfHMFs(F, prec);
> bbs := NarrowClassGroupReps(GrRing);
> bb:=bbs[1];
> ZF:=Integers(F);
> MaxGenWeight := 10;
> MaxRelWeight := 20;
> p := 1;
> TestLevel := p*ZF;
>
>
> time g,r,m:=ConstructGeneratorsAndRelationsOnComponent(GrRing,TestLevel,MaxGenWeight, bb);

and get the following error:

ConstructGeneratorsAndRelationsOnComponent(
M: Graded ring of Hilbert modular forms over Quadratic Field wi...,
N: Principal Ideal Generator: 1,
MaxWeight: 10,
bb: Principal Ideal Generator: 1
)
SpecifiedComponentBasis(
Mk: Space of Hilbert modular forms over Quadratic Field with def...,
bb: Principal Ideal Generator: 1
)
LinearDependence(
List: [ Coefficients for component ideal class bb = Principal Idea...
)
In file "C:\Users\angel\OneDrive\Documents\GitHub\hmf-master\hilbertmodularforms\ModFrmHilD\Elements.m", line 1037, column 11:
>>     Append(~L, CoefficientsOfForm);
             ^
Runtime error in 'Append': Cannot coerce element into the universe



It seems like a minor issue (the coefficients of the form added to linear dependence aren't rational), but I'd appreciate some help!

**Comment by edgarcosta** [comment]
It took a while to fix all the underlying issues, but now I get a new bug:

```
> load "config.m";
Loading "config.m"
> prec := 10;
> D := 12;
> F:=QuadraticField(D);
> GrRing := GradedRingOfHMFs(F, prec);
> bbs := NarrowClassGroupReps(GrRing);
> bb:=bbs[1];
> ZF:=Integers(F);
> MaxGenWeight := 10;
> MaxRelWeight := 20;
> p := 1;
> TestLevel := p*ZF;
> SetDebugOnError(true);
> time g,r,m:=ConstructGeneratorsAndRelationsOnComponent(GrRing,TestLevel,MaxGenWeight, bb);


ConstructGeneratorsAndRelationsOnComponent(
M: Graded ring of Hilbert modular forms over Quadratic Field wi...,
N: Principal Ideal Generator: 1,
MaxWeight: 10,
bb: Principal Ideal Generator: 1
)
FindNewGenerators(
Mk: Space of Hilbert modular forms over Quadratic Field with def...,
EvaluatedMonomials: [ Coefficients for component ideal class bb = Principal Idea...,
BasisWeightK: [ Coefficients for component ideal class bb = Principal Idea...
)
In file "/Users/edgarcosta/Dropbox (Personal)/projects/hilbertmodularforms/ModFrmHilD/CanonicalRing/CanonicalRing.m", line 143, column 10:
>>   W := sub<V | [MonomialCoeffLists[i] : i in [1..#EvaluatedMonomials]]>;
            ^
Runtime error in sub< ... >: Rhs argument 1 is invalid for this constructor

```

**Comment by edgarcosta** [comment]
I tracked down the issue above to different labeling conventions for components when compared to  Dasgupta, Darmon, Pollack.

Meanwhile, I broke, `ConstructGenerators*`, which I will fix tomorrow

**Comment by edgarcosta** [comment]
Fixed
```
> load "config.m";
Loading "config.m"
> prec := 10;
> D := 12;
> F:=QuadraticField(D);
> GrRing := GradedRingOfHMFs(F, prec);
> bbs := NarrowClassGroupReps(GrRing);
> bb:=bbs[1];
> ZF:=Integers(F);
> MaxGenWeight := 10;
> MaxRelWeight := 20;
> p := 1;
> TestLevel := p*ZF;
> SetDebugOnError(true);
> time g,r,m:=ConstructGeneratorsAndRelationsOnComponent(GrRing,TestLevel,MaxGenWeight, bb);
weights of ev = [
[ 4, 4 ],
[ 4, 4 ],
[ 4, 4 ]
]
weights of basis = [
[ 4, 4 ],
[ 4, 4 ],
[ 4, 4 ],
[ 4, 4 ]
]
bb = Principal Ideal
Generator:
1
weights of ev = [
[ 6, 6 ],
[ 6, 6 ],
[ 6, 6 ],
[ 6, 6 ],
[ 6, 6 ]
]
weights of basis = [
[ 6, 6 ],
[ 6, 6 ],
[ 6, 6 ],
[ 6, 6 ],
[ 6, 6 ],
[ 6, 6 ]
]
bb = Principal Ideal
Generator:
1
weights of ev = [
[ 8, 8 ],
[ 8, 8 ],
[ 8, 8 ],
[ 8, 8 ],
[ 8, 8 ],
[ 8, 8 ],
[ 8, 8 ],
[ 8, 8 ],
[ 8, 8 ],
[ 8, 8 ],
[ 8, 8 ]
]
weights of basis = [
[ 8, 8 ],
[ 8, 8 ],
[ 8, 8 ],
[ 8, 8 ],
[ 8, 8 ],
[ 8, 8 ],
[ 8, 8 ],
[ 8, 8 ]
]
bb = Principal Ideal
Generator:
1
weights of ev = [
[ 10, 10 ],
[ 10, 10 ],
[ 10, 10 ],
[ 10, 10 ],
[ 10, 10 ],
[ 10, 10 ],
[ 10, 10 ],
[ 10, 10 ],
[ 10, 10 ],
[ 10, 10 ],
[ 10, 10 ],
[ 10, 10 ]
]
weights of basis = [
[ 10, 10 ],
[ 10, 10 ],
[ 10, 10 ],
[ 10, 10 ],
[ 10, 10 ],
[ 10, 10 ],
[ 10, 10 ],
[ 10, 10 ],
[ 10, 10 ],
[ 10, 10 ]
]
bb = Principal Ideal
Generator:
1
Time: 354.010
>

Total time: 363.730 seconds, Total memory usage: 44393.94MB
```
