### ISSUE TITLE
Make CanonicalRing computation trivial for Q(sqrt(13))

### ISSUE THREAD

**Issue by edgarcosta** [edgarcosta/hilbertmodularforms#144]

**Comment by assaferan** [comment]
Hi Edgar, I think I misled you to choose Q(sqrt(2)), but it might actually be better to start with Q(sqrt13). (class number 1 and only two units in the unit group of the quaternion algebra).

**Comment by edgarcosta** [comment]
the goal is to be able to compute the canonical ring in a matter of minutes...
