### ISSUE TITLE
Tests for traces sometimes fail

### ISSUE THREAD

**Issue by assaferan** [edgarcosta/hilbertmodularforms#145]
This is a randomized test, and somewhat slow, so I have only one instance that I can point to right now:
d = 60, k = 16, n = 4.
> d := 60;
> k := 16;
> n := 4;
> F := QuadraticField(d);
> ZF := Integers(F);
> prec := 1;
> R := GradedRingOfHMFs(F, prec);
> Trace(HMFSpace(R, n*ZF, [k, k]), 1*ZF);
10813
> STrace(HMFSpace(R, n*ZF, [k, k]), 1*ZF);
10812

**Comment by BenKBreen** [comment]
I will look into this today / weekend. 

I had some issues when the level was divisible by a power of 2^n. I (hopefully) ironed them out for the STrace function, but I am not sure that I fixed them for the Trace function as well.

**Comment by assaferan** [comment]
You're welcome, I just wanted to make sure the new feature (of actually computing the correct space corresponding to the Hecke character) is working. 
ps: my guess is that Ben has already compensated for it in the trace formula, but we will have to look into it.

**Comment by edgarcosta** [comment]
for d in [5 8 12 13 17 20 21 24 28 29 32 33 37 40 41 44 45 48 52 53 56 57 60 61 65 68 69 72 73 76 77 80 84 85 88 89  93 96 97]
these are things are off:
```
Testing d=60
ERROR k=4, n=4: Trace(1) = 445 != 444 = Dimension
ERROR k=6, n=4: Trace(1) = 1213 != 1212 = Dimension
ERROR k=8, n=4: Trace(1) = 2365 != 2364 = Dimension
ERROR k=10, n=4:        Trace(1) = 3901 != 3900 = Dimension
ERROR k=12, n=4:        Trace(1) = 5821 != 5820 = Dimension
ERROR k=14, n=4:        Trace(1) = 8125 != 8124 = Dimension
ERROR k=16, n=4:        Trace(1) = 10813 != 10812 = Dimension
Done d=60 44.780s

Testing d=28
ERROR k=4, n=4: Trace(1) = 79 != 77 = Dimension
ERROR k=6, n=4: Trace(1) = 207 != 205 = Dimension
ERROR k=8, n=4: Trace(1) = 399 != 397 = Dimension
ERROR k=10, n=4:        Trace(1) = 655 != 653 = Dimension
ERROR k=12, n=4:        Trace(1) = 975 != 973 = Dimension
ERROR k=14, n=4:        Trace(1) = 1359 != 1357 = Dimension
ERROR k=16, n=4:        Trace(1) = 1807 != 1805 = Dimension
Done d=28 149.860s
```

note that for all of them STrace is correct

**Comment by BenKBreen** [comment]
Just submitted a fix. 

The issue occurred when the level contained a prime above 2 and was due to the fact that the discriminant of the algebra ZF[x] / ( x^2 - 1 ) is divisible by 2. This was fixed by finding a polynomial p(x) = x^2 + ax + b such that ZF[x] / p(x) splits and b^2 - 4a is not divisible by 2. I think we can now update the test cases for Trace and STrace to include arbitrary level.

**Comment by edgarcosta** [comment]
```
> d := 60;
> k := 16;
> n := 4;
> F := QuadraticField(d);
> ZF := Integers(F);
> prec := 1;
> R := GradedRingOfHMFs(F, prec);
> M := HMFSpace(R, n*ZF, [k, k]);
> CuspDimension(M);
5406
> Trace(M, 1*ZF);
5406
```
