### ISSUE TITLE
Problem with coefficient ring returned from HilbertCuspForms

### ISSUE THREAD

**Issue by assaferan** [edgarcosta/hilbertmodularforms#153]
```
function get_field()
F := QuadraticField(5);
ZF := Integers(F);
hcf := HilbertCuspForms(F, 1*ZF, [6,6]);
S := NewSubspace(hcf);
fs :=  [* Eigenform(U) :  U in NewformDecomposition(S) *];
return Parent(HeckeEigenvalue(fs[1], 2*ZF));
end function;
```

Without attaching our package this is the rationals, else it is a degree 4 field. (the splitting field of the quaternion algebra?)

**Comment by edgarcosta** [comment]
https://github.com/edgarcosta/hilbertmodularforms/blob/master/ModFrmHil/finitefield.m#L304 is the issue

**Comment by assaferan** [comment]
Yes, I saw that (it appears in one more place). But when I copied the code
of the missing function I'm failing a different test, so I haven't
committed anything yet.
