### ISSUE TITLE
Igusa pullback no working as expected

### ISSUE THREAD

**Issue by edgarcosta** [edgarcosta/hilbertmodularforms#178]
Perhaps an issue with the implementation and the nontrivial unitchar
```
> F := QuadraticField(12);
> ZF := Integers(F);
> prec:=6;
> M := GradedRingOfHMFs(F, prec);
> S4plus, S4minus := SiegelEisensteinPullback(M,[4,4]);
> S6plus, S6minus := SiegelEisensteinPullback(M,[6,6]);
> B4 := Basis(HMFSpace(M, [4, 4]));
> LinearDependence(B4 cat [S4plus]);
[
[ 23, -23, 2520, 0, -46 ]
]
> B6:=Basis(HMFSpace(M, [6,6]));
> LinearDependence(B6 cat [S6plus]);
[
[ 122713, -122713, -15007608, 0, -7161, 0, -245426 ]
]
>
> B10:=Basis(HMFSpace(M, [10,10]));
> LinearDependence([S4minus*S6minus] cat B10);
[]
```

**Comment by edgarcosta** [comment]
Perhaps one could start by trying to see if 
```
(S4plus*S6minus)/S6minus eq S4plus
```
but one needs to do this only on the component that is nonzero, otherwise were trying to divide by zero on one of the components

**Comment by ababei** [comment]
How do we check what the unit character is for S4minus? I think I get trivial unit character for both, it might be messing up the multiplication.

> comp1:=Components(S4minus)[ZF.1];
> comp1;
Component of Hilbert modular form expansion with precision 6.
Parent: Space of Hilbert modular forms over Quadratic Field with defining polynomial x^2 - 3 over the Rational Field
Precision: 6
Weight: [ 4, 4 ]
Character: 1
Level: 1
Coefficients for component ideal class bb = Principal Ideal
Generator:
1

        (Trace, nu)  |--->   a_nu
        (0, 0)  |--->   0
        (1, 1/2*$.1 + 1/6*$.2)  |--->   0
        (1, 1/2*$.1)  |--->   0
        (2, 1/1*$.1 + 1/3*$.2)  |--->   0
        (2, 1/1*$.1 + 1/6*$.2)  |--->   0
        (2, $.1)  |--->   0
        (2, 1/1*$.1 - 1/6*$.2)  |--->   0
        (3, 3/2*$.1 + 1/2*$.2)  |--->   0
        (3, 3/2*$.1 + 1/3*$.2)  |--->   0
        (3, 3/2*$.1 + 1/6*$.2)  |--->   0
...


> UnitCharacter(comp1);
Character of the totally positive unit group of Quadratic Field with defining polynomial x^2 - 3 over the Rational Field defined by values [ 1 ] on generators
> comp2:=Components(S4minus)[ZF.2];

> comp2;
Component of Hilbert modular form expansion with precision 6.
Parent: Space of Hilbert modular forms over Quadratic Field with defining polynomial x^2 - 3 over the Rational Field
Precision: 6
Weight: [ 4, 4 ]
Character: 1
Level: 1
Coefficients for component ideal class bb = Principal Ideal
Generator:
$.2

        (Trace, nu)  |--->   a_nu
        (0, 0)  |--->   0
        (1, 1/2*$.1)  |--->   120
        (2, $.1)  |--->   960
        (3, 3/2*$.1 + 1/2*$.2)  |--->   0
        (3, 3/2*$.1)  |--->   -3240
        (4, 2/1*$.1 + 1/2*$.2)  |--->   -8400
        (4, 2/1*$.1)  |--->   7680
        (4, 2/1*$.1 - 1/2*$.2)  |--->   -8400
        (5, 5/2*$.1 + 1/2*$.2)  |--->   0
        (5, 5/2*$.1)  |--->   30000
...

> UnitCharacter(comp2);
Character of the totally positive unit group of Quadratic Field with defining polynomial x^2 - 3 over the Rational Field defined by values [ 1 ] on generators

**Comment by edgarcosta** [comment]
I will check this out in a couple of hours.

**Comment by ababei** [comment]
I dug a bit deeper and the issue seems to be while creating the component; for example, on line 129 in Igusa.m, we define

> fminus:=HMF(HMFComp(Mkminus, bb, fminuscoeffs));

but asking for the unit character of HMFComp(Mkminus, bb, fminuscoeffs) gives the trivial one, even if Mkminus has the -1 character.

**Comment by edgarcosta** [comment]
I will fix this

**Comment by edgarcosta** [comment]
The unit character not being properly set has been fixed but `S4minus*S6minus` is still not in the span of `B10`.
