### ISSUE TITLE
EisensteinBasis

### ISSUE THREAD

**Issue by ahorawa** [edgarcosta/hilbertmodularforms#184]
I ran:
```
F:=QuadraticField(5);
prec:=20;
M:=GradedRingOfHMFs(F, prec);
ZF:=Integers(F);
N:= 31*ZF;
H := HeckeCharacterGroup(N, [1,2]);
chi1, chi2 := Explode([H.1, H.2]);
chi := chi1*chi2;
Mchi := HMFSpace(M, N, [1,1], chi);
Bchi := EisensteinBasis(Mchi);
```
and got
```
EisensteinBasis(
Mk: Space of Hilbert modular forms over Quadratic Field with def...
)
In file "/Users/alexh/Documents/Michigan/mathematics/Computations/HMS/hilbertmodularforms/ModFrmHilD/Basis.m", line 88, column 5:
>>     assert #Mk`EisensteinBasis eq EisensteinDimension(Mk);
       ^
Runtime error in assert: Assertion failed
```

**Comment by edgarcosta** [comment]
I think this is #161

**Comment by ahorawa** [comment]
I don't get why we need to implement "admissible" for this... Dasgupta-Kakde say:
<img width="825" alt="Screen Shot 2022-02-23 at 8 41 27 PM" src="https://user-images.githubusercontent.com/50548394/155441124-025bed72-beec-4f67-8a4c-fa241c044075.png">
Since you already compute all the admissible characters, isn't the dimension of the space just their total number?

**Comment by edgarcosta** [comment]
Hmm, maybe, but I did not check if a pair `(m,n)` is admissible, as before we were focused on even weight, and we don't need to worry about admissibility.

Regardless, I need to investigate this further, I hope get in today at about 10

**Comment by edgarcosta** [comment]
Hmm, I take it back, something fishier is going on
```
debug> p EisensteinDimension(Mk)
1
debug> p #Mk`EisensteinBasis
8
debug> p LinearDependence(Mk`EisensteinBasis)
[]
debug>
```
