### ISSUE TITLE
Relations among only some generators

### ISSUE THREAD

**Issue by jvoight** [edgarcosta/hilbertmodularforms#195]
For our K3 example, we found we often wanted to compute the graded ring on just some subset of generators, which we could think of as being the analogue of an incomplete linear series.  

For example, we might want all of the weight 2 generators and one weight 4 generator; projection onto the weight 2 generators could give a branched cover structure.

If we have the full graded ring, this can be accomplished with an elimination ideal--but of course in big examples, this chokes and dies.  We'd like to be able to do it intrinsically using q-expansions.  

A first version could just take as input pairs <weight, basis element>; the linear algebra code should function the same, I think!  If we wanted something more advanced, we could take a sequence of elements of HMFspaces, so then the user could sums of basis elements.

**Comment by a-kulkarn** [comment]
@jvoight What do you think of the following?

```
// Test to compute relations among only some of the elements of the canonical ring via linear algebra.

K  := QuadraticField(5);
ZK := MaximalOrder(K);
P  := Factorization(31*ZK)[1][1];

// Construct the HMF Mothership.
prec := 10;
R := GradedRingOfHMFs(K, prec);

// Compute the space of 2-forms and a singular 4-form.
W2 := HMFSpace(R, P, [2,2]);
W4 := HMFSpace(R, P, [4,4]);
time f := Basis(W4)[1];
forms := [* g : g in Basis(W2) *] cat [* f *];

// Compute the image of the HMS under the rational map determined by forms.
// The user needs to tell it the degrees to look for Syzygies. We don't have a degree bound for the
// degree of the relations of a projection, not to mention precision issues, so we insist that the user
// chooses a degree bound explicitly.
X := HilbertModularImage(forms : MaxRelationDegree := 10);
assert Dimension(X) eq 2;
```
Output of `print X`
```
Scheme over Rational Field defined by
$.1^2 - $.4
```

**Comment by a-kulkarn** [comment]
> Or by singular you mean "single"?

I meant single.

> If the degree bound is required as part of the input, then it shouldn't be a vararg. So X := HilbertModularImage(forms, 10);. OTOH, if we just want to search up to whatever bound is possible given the working precision, then it would make sense to keep this a vararg. I'm not sure we're consistent in this across the package.

Yeah, this is tricky. Perhaps in some distant future there is a guaranteed bound on the relations that can be determined just from the forms themselves, something like the macaulay degree for finding the Syzygies between a set of polynomials. In that sense, the program can decide on a default maximum relation degree without the input of the user. Assuming we can compute the canonical model with certified relations, this is in principle possible.

On the other hand, there may not be enough precision for this function to terminate correctly. The other way of deciding on the default maximum is "what is the maximum degree where I can reliably find the relations, given the input precision". In this sense, demanding that the user make this choice is the easiest for us.

**Comment by jvoight** [comment]
Yes exactly.  Too hard to have something in theory, at least for now.  So (sorry to repeat myself) I think we should either 
  * require a choice by the user, so not vararg, or 
  * keep the vararg and just test relations up to whatever bound is possible given the working precision.  
And I agree, the first option is easier.

**Comment by a-kulkarn** [comment]
I went with the first one. I guess we close the issue?
