### ISSUE TITLE
Hecke operators issues

### ISSUE THREAD

**Issue by BenKBreen** [edgarcosta/hilbertmodularforms#21]
I think there are currently two issues in the Hecke operators.

1) Small one,  I think 

ideals := Ideal(f);       =>     ideals := Ideals(f);

2) Bigger one, 

When we create the HMF Space, it has a fixed precision and a dictionary that assigns values to the a_nu. To run the heck operator T(N), I think we we need a dictionary that scales with the value N as seen from this snippet of code. 

for i:=1 to #ideals do
    c := 0;
    for aa in Divisors(ideals[i] + nn) do             

where nn = N  for hecke operator T(N). I wasn't sure how to fix this and I figured it would be best to correct both these issues at the same time

**Comment by jvoight** [comment]
+1 to run the heck

**Comment by ababei** [comment]
I have a fix for the second issue, but it gives T(n)f with lower precision, prec/Norm(n). To make sure this is enough precision to uniquely determine the modular form, we can reconstruct it with a basis for the space, but loading a basis can take time, so I'll include a version of the function to input a precomputed basis.

**Comment by jvoight** [comment]
The second bit should be solved in issue #62.
