### ISSUE TITLE
Bug in EisensteinDimension

### ISSUE THREAD

**Issue by assaferan** [edgarcosta/hilbertmodularforms#241]
For non-trivial character, the construction of Galois conjugacy representatives is wrong. 
An example is 
```
> F := QuadraticField(79);
> N := PrimeIdealsOverPrime(F, 7)[1];
> X<eta, eps> := HeckeCharacterGroup(N, [1,2]);
> chi := eps^2;
> R := GradedRingOfHMFs(F,1);
> M := HMFSpace(R, N, [2,2], chi);
> EisensteinDimension(M);
16
```
where the dimension should be 12.

**Comment by edgarcosta** [comment]
still a bug

**Comment by edgarcosta** [comment]
this seems to no longer be a bug. @abhijit-mudigonda Do you confirm?

**Comment by abhijit-mudigonda** [comment]
This particular thing is no longer an issue, I think. There may still be issues in EisensteinDimension, but we can probably close this issue.
