### ISSUE TITLE
Cusp resolution when D = 24, gamma = (+,+), N = 1.

### ISSUE THREAD

**Issue by ahorawa** [edgarcosta/hilbertmodularforms#265]
```
F := QuadraticField(24);
N := 1*Integers(F);
B := 1*Integers(F);
gamma := Gamma0(F, N, B);
CuspsWithResolution(gamma); 
```
The self-intersection numbers of the cusp resolutions are [-6, -2], but according to pp. 175 of vdG, they should be [-2, -2]. Perhaps I'm reading this wrong...

**Comment by edgarcosta** [comment]
@j-kieffer, do you have any opinion on this?

**Comment by ahorawa** [comment]
Ok, if you're sure the answer is correct and vdG is wrong, then let's table this for now. He uses this in the proof of one of his main classification theorems, but I guess the theorem may still be true with a different proof.
