### ISSUE TITLE
Implement multiplication for higher degree fields

### ISSUE THREAD

**Issue by edgarcosta** [edgarcosta/hilbertmodularforms#3]

**Comment by edgarcosta** [comment]
@BenKBreen is looking into http://www.lmfdb.org/NumberField/3.3.49.1

**Comment by BenKBreen** [comment]
A primitive version of the code has been completed for totally real cubic fields with narrow class number 1. For timing, it looks like we can get set up ~1500 coefficients in 7.5 seconds and ~3000 in 35 seconds.

I would like to clean up this code to minimize headaches for Edgar. This mainly involves the following function 

 IndicesByTrace(n):   This returns all totally positive elements of trace n.
             I wrote a hacky version for cubic fields that runs quickly but is messy. I would like to 
                              a.) find a clean, fast algorithm.
                              b.) have it run for arbitrary totally real fields.
John has lots of good suggestions on this. If we could do this, the project would be complete.

**Comment by abhijit-mudigonda** [comment]
Resolved by https://github.com/edgarcosta/hilbertmodularforms/pull/364
