### ISSUE TITLE
Bug in dimension of cusp forms from trace formula when k = 2

### ISSUE THREAD

**Issue by assaferan** [edgarcosta/hilbertmodularforms#321]
The following code demonstrates the problem by failing (now a test):

d := 473;
F := QuadraticField(d);
ZF := Integers(F);
N := 1*ZF;
printf "(%o;%o;%o),", d,IdealOneLine(N),k;
testTraceDimension(F,N,k);
prec := 1;
R := GradedRingOfHMFs(F, prec);
hmf := HMFSpace(R, N, [k,k]);
dim_trace := CuspDimension(hmf : version := "trace");
delete hmf`CuspDimension;
dim_builtin := CuspDimension(hmf : version := "builtin");
assert dim_trace eq dim_builtin;

**Comment by BenKBreen** [comment]
Hi all, 

Sorry - I was hoping to push my correction factor for the trace formula for parallel weight (2,...,2), but I haven't had time with the wedding. I'll push by the end of the weekend, and this issue should be resolved. 

In the meantime, if you just want the dimension of the space (Trace of 1*ZF), the correction factor should be the size of the 2-torsion subgroup of the narrow class group. Here is code for that

C := NarrowClassGroup(F);
hplustwo := #[i : i in C | 2*i eq C!0 ];

**Comment by assaferan** [comment]
Thanks Ben! 
Yes, I figured out it's something like that (coming from splitting by character), but something went wrong when trying to apply it directly and a bunch of other sets failed. If your correction passes the tests, I'll just wait until you push it and this will be resolved.

**Comment by BenKBreen** [comment]
I just pushed the changes to the trace formula in weight (2,..,2). I think this resolved the issue, but let me know if anything is still broken.

**Comment by edgarcosta** [comment]
tks! I have reenabled the tests
