### ISSUE TITLE
Dimensions tests sometimes fail

### ISSUE THREAD

**Issue by BenKBreen** [edgarcosta/hilbertmodularforms#332]
The dimension test sometimes fails with the error "the operation was cancelled."

I think this is due to time limit / memory issues? The example that failed for me was with discriminant D = 321, level N = 1, and 
weight k = [12, 12]. I believe the computation for `Dimension(HilbertCuspForms(F,N,[k,k]));` timed out -- but I was able to run this example on my computer in 15 minutes and with 11GB of memory. 

The trace formula is now fixed -- If everyone is okay with it, I can update the code to compute the dimensions using the trace (I believe that is what was implemented earlier). In this case, the code to get the dimension from trace (over all characters) is  
  
```prec := 1;
ZF := Integers(F);
R := GradedRingOfHMFs(F, prec);
hmf := HMFSpace(R, N, [k,k]);
dim_hmf := TraceProduct(hmf, 1*ZF, 1*ZF);
if k eq 2 then 
   hplus := NarrowClassNumber(F);
   dim_hmf -:= hplus;
end if;

**Comment by assaferan** [comment]
Hi Ben,
Yes, I think we are all okay with it. 
Note that the Dimensions test specifically tests the validity of the trace formula for some random spaces, and for the example we had with D = 473 and k = 2 so I wouldn't drop it off completely, but we can maybe limit further the weights for which it computes the dimensions using explicit construction of the spaces.
My current suggestion is to limit the weight to k <= 10, makes sense?

**Comment by assaferan** [comment]
Oh, I see now that it is much easier to fix - at the moment, because the trace formula had bugs, I was testing the dimension formula against the built in dimension. But now we can check it against the trace formula instead! I'm on it.

**Comment by assaferan** [comment]
Should be taken care of in PR #334
