### ISSUE TITLE
verify that defining equations for HilbertModularSurfaces are still correct

### ISSUE THREAD

**Issue by abhijit-mudigonda** [edgarcosta/hilbertmodularforms#371]
https://github.com/edgarcosta/hilbertmodularforms/pull/364 changed the equations in the Surface_Qsqrt13.m test without confirming that the new scheme was actually the same as the old. We should confirm that the code indeed still works.

**Comment by assaferan** [comment]
@SamSchiavone - I wanted to run the sqrt13-verification.m script to verify, but wasn't sure what's going on there. Any help would be appreciated.

**Comment by assaferan** [comment]
This is verified in PR #378
