### ISSUE TITLE
Dictionaries for faster multiplication

### ISSUE THREAD

**Issue by michaelmusty** [edgarcosta/hilbertmodularforms#61]
It would be nice if we implemented dictionaries to speed up the multiplication/addition, but until we get a bit more functionality I think the general consensus is to focus on other matters with our limited time. If multiplication starts to be the bottleneck after we do some testing, then maybe this can move up higher on the task list. If there are comments or concerns about this we can discuss them here. Sound good @edgarcosta ?

**Comment by edgarcosta** [comment]
Sounds good!

**Comment by abhijit-mudigonda** [comment]
I'm closing this because we do multiplication in a different way.
