### ISSUE TITLE
Graded ring, spaces, and elements

### ISSUE THREAD

**Issue by michaelmusty** [edgarcosta/hilbertmodularforms#63]
New proposed data structure for spaces of HMFs:

ModFrmHilDGRng: The graded ring M(Gamma) which is currently type ModFrmHilD. So we want to replace all ModFrmHilD with ModFrmHilDGRng. A ModFrmHilDGRng stores the global multiplication table for elements of all its components (which are of type ModFrmHilD).

ModFrmHilD: The space of HMFs for a given weight, level, and character. The parent of a ModFrmHilD is a ModFrmHilDGRng. Elements of a ModFrmHilD are of type ModFrmHilDElt.

ModFrmHilDElt: An HMF. Parent is a space (type ModFrmHilD).

**Comment by edgarcosta** [comment]
Sounds good to me.

**Comment by michaelmusty** [comment]
OK. This has now been "completed". I'm sure this will cause some bugs, so please report and we can squash them together!
