### ISSUE TITLE
Number of Eisenstein series for Cl^+(F) > 1 is off? 

### ISSUE THREAD

**Issue by BenKBreen** [edgarcosta/hilbertmodularforms#67]
I need help interpreting the formulas for Eisenstein series in

Dasgupta, Darmon, Pollack - Hilbert Modular Forms and the Gross-Stark Conjecture

on pg. 458-459. We seem to be getting too many Eisenstein series as of right now.  Let K = QQ(sqrt(12)) and M_2 the space of trivial level and parallel weight [2,2] forms. According to dimension formulas  Dim(M_2) = 1 but we are currently producing 2 Eisenstein series.

**Comment by edgarcosta** [comment]
What does the formula in Cohen and Stroemberg says in this case?
