### ISSUE TITLE
Overloaded functions

### ISSUE THREAD

**Issue by BenKBreen** [edgarcosta/hilbertmodularforms#72]
Originally noted by Mike

The type of an HMF (ModFrmHilElt) is from the internal magma code for producing Newforms. We don't want to overload any preexisting magma functions.

For example:
Ours:   Basefield(f) -> Number field for the form f.
Preexisting function:   Basefield(f) -> The field over which the coefficients of f are defined.

**Comment by edgarcosta** [comment]
Any other examples? 
and what is the underlying issue? Do we imagine one day that ModFrmHilDElt will be an extension of ModFrmHilElt? 

ps: I feel extremely conflicted regarding that example, I understand that we can't change Magma's function names, but they should have called that  `CoefficientField`.

**Comment by BenKBreen** [comment]
This was the only example that we have seen so far.  Ahh, I didn't even catch the difference in types (ModFrmHilDElt vs. ModFrmHilElt). Thanks!

I think our function Basefield(f) (see elements line 112) is overloaded. I thought that it was with the  internal Basefield(f), but that takes type ModFrmHilElt and not ModFrmHilDElt as you pointed out.

Here is some code to reproduce the bug

load "config.m";
F := QuadraticField(5);
M := GradedRingOfHMFs(F,10);
M2 := HMFSpace(M,[2,2]);
B := Basis(M2);
f := B[1];
BaseField(F); 
BaseField(Parent(Parent(f)));

I'll look into this more tonight!
