### ISSUE TITLE
HMFWorkspace

### ISSUE THREAD

**Issue by edgarcosta** [edgarcosta/hilbertmodularforms#9]
Figure out a data structure, so we cache all the basis computed so far, and we are able to save them to a file/folder.

Perhaps with a global object `HMFworkspace`
that we can initialize with 
- `HMFworkspace( field, prec)` or 
- `HMFworkspace( file )`  == load file

We would also need to implement something along the lines
- `HMFworkspace_save( file )`

**Comment by edgarcosta** [comment]
Attributes so far: 
- Field

- Precision

- Generators for the Ideals

- Representatives for the narrow class group

- Multiplication Table

- EigenForms - an  Associative Array
    (weight, level, character) --> list of eigenforms

**Comment by abhijit-mudigonda** [comment]
@edgarcosta can I close this? I think we have most of these things and Workspace.m is deprecated anyways.
